vecMapMovie = True
vecMapBorderMovie = False
vecMovie = True
streamLines = False
vecMovieConst = False
vecShow = False
randomize = True
move_along = True
vel_weighting = True
timePlot = False
magMovie = False
vecPDF = False
raw = False
smooth = 'None'  # 'fourier', 'gauss', 'svd'
temp_filt = True
vcmap = 'hot'
corrMovie = False
drange = (-45, 0)
dpi = 300
seed_count = 1000
rnd_val = 0.05
sf = 2.0
cmapmax = 'prc99.9'  # 'prc99.9', 'prc99' (99th percentile of velocity mag), 'max' (max vel mag), number (float value)